---
version: "3.9"
services:
  devopsdb:
    image: rajagadi/automation:db
    ports:
      - "3306:3306"
    networks:
      - mynetworks
    deploy:
      replicas: 3

  application:
    image: rajagadi/automation:app
    ports:
      - "1111:8080"
    depends_on:
      - devopsdb
    networks:
      - mynetworks
    

networks:              # ✅ top level — same indentation as services
  mynetworks:          # ✅ mapping not a list
    driver: overlay
