---
version: "3"
services:
 devopsdb:
   image: rajagadi/automation:db
   ports:
     - "3306:3306"
   deploy: 
     replicas: 3

 application:
   image: rajagadi/automation:app
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
   deploy: 
     replicas: 3
